export { default as NavLink } from './nav-link'
export { default as Loading } from './loading'
export { default as Contact } from './contact'
export { default as NavBar } from './nav-bar'
export { default as Footer } from './footer'
